name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowViewer.Core
      Configuration: Release
    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
        
      - name: Build Packages
        run: |
          dotnet restore $env:Solution_Name/$env:Solution_Name.csproj
          msbuild $env:Solution_Name/$env:Solution_Name.csproj -t:rebuild -property:Configuration=$env:Configuration
      