name: Publish Nuget Packages

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowViewer.Core
    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      # 缓存 NuGet 包
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ env.Solution_Name }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate Release Tag
        shell: pwsh
        run: |
          $date = Get-Content "ShadowViewer.Core/.version/date.txt" -Raw
          $number = Get-Content "ShadowViewer.Core/.version/number.txt" -Raw
          $date = $date.Trim()
          $number = $number.Trim()
          $year = $date.Substring(0, 4)
          $month = [int]$date.Substring(5, 2)
          $day = [int]$date.Substring(8, 2)
          $releaseTag = "$year.$month.$day.$number"
          "RELEASE_TAG=$releaseTag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Use Release Tag
        run: echo "The release tag is $env:RELEASE_TAG"
      - name: Create NugetPackages
        run: |
          cd ..\..
          mkdir NugetPackages

      - name: Build Packages
        run: |
          dotnet restore $env:Solution_Name/$env:Solution_Name.csproj
          dotnet build $env:Solution_Name/$env:Solution_Name.csproj -p:Configuration=Release
      - name: Push package to Nuget registry
        run: |
          cd ..\..\NugetPackages
          ls
          dotnet nuget push "*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY --skip-duplicate        
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      
      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}" 
          title: "${{ env.RELEASE_TAG }}"
          automatic_release_tag: "${{ env.RELEASE_TAG }}"
          prerelease: false
          # files: |
          #   build/libs/*
