name: Get Latest Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-latest-tag:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get latest tag
      shell: pwsh
      run: |
        $currentDate = (Get-Date).ToString("yyyy.MM.dd")
        $tag = (git describe --tags $(git rev-list --tags --max-count=1))
        $tagParts = $tag -split "\."
        $tagDate = "$($tagParts[0]).$($tagParts[1]).$($tagParts[2])"
        $tagNumber = [int]$tagParts[3]
        if ($tagDate -eq $currentDate) {
            $newTagNumber = $tagNumber + 1
        } else {
            $newTagNumber = 1
            $tagDate = $currentDate
        }
        $newTag = "$tagDate.$newTagNumber"
        echo "NEW_TAG=$newTag" >> $GITHUB_ENV

    - name: Show latest tag
      run: echo "${NEW_TAG}"
